name: ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: Debug

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        compiler:
          - llvm-14
          - gcc-11
        build_type:
          - Debug
          #- Release
    steps:
    - uses: actions/checkout@v3

    - name: Install compiler
      id: install_cc
      uses: krogk/cpp-project-template/.github/actions/action@develop
      with:
        compiler: ${{ matrix.compiler }}
    - name: Check compiler
      shell: bash
      env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
      run: |
        $CC --version
        $CXX --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install setup tools
      run: pip3 install wheel setuptools
      shell: bash

    - name: Install conan latest
      if: ${{ inputs.version == '' }}
      run: pip3 install conan --upgrade
      shell: bash

    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Update profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
    - name: Install dependencies
      run: conan install . -s build_type=${{ matrix.build_type }} --install-folder=${{github.workspace}}/build --build missing

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      # Build program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}