name: ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BUILD_TYPE: Debug

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        compiler:
          - llvm-14
          - gcc-11
        build_type:
          - Debug
          #- Release
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install setup tools
      run: pip3 install wheel setuptools
      shell: bash

    - name: Install conan latest
      if: ${{ inputs.version == '' }}
      run: pip3 install conan --upgrade
      shell: bash

    - name: Create default profile
      run: conan profile new default --detect
      
    - name: Update profile
      if: ${{ runner.os  == 'Linux' }}
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
      
    - name: Install dependencies
      run: conan install . -s build_type=${{ matrix.build_type }} --install-folder=${{github.workspace}}/build --build missing

    - name: Install compiler
      id: install_cxx
      run: |
        echo Install "${{ matrix.compiler }}" on "${{ runner.os }}"
        .${GITHUB_ACTION_PATH}/compiler-setup.sh "${{ runner.os }}" "${{ matrix.compiler }}"
        ${{ matrix.compiler }}

    - name: Check compiler
      shell: bash
      env:
          CC: ${{ steps.install_cxx.outputs.cc }}
          CXX: ${{ steps.instalinstall_cxxl_cc.outputs.cxx }}
      run: |
        $CC --version
        $CXX --version

    - name: Build
      working-directory: ${{github.workspace}}
      # Build program with the given configuration
      run: .${{github.workspace}}/build.sh -d -v

    - name: Test
      working-directory: ${{github.workspace}}
      # Execute tests defined by the script
      run: .${{github.workspace}}/test.sh -a